language: python
python:
  - 2.7
  - 3.6

install:
  - pip install coverage coveralls
  - pip install pycodestyle
script:
  - pycodestyle .
  - coverage run --source=src setup.py test
after_success:
  - coveralls
